// src/entrypoints/popup/App.vue
<template>
	<div class="popup-container">
		<div class="header">
			<h2>🎬 GifShot</h2>
			<p>屏幕录制 GIF 插件</p>
			<button @click="openFullApp" class="open-app-btn">🚀 完整版</button>
		</div>

		<div class="content">
			<div v-if="!isRecording && !gifPreview" class="record-options">
				<h3>选择录制类型</h3>
				<div class="option-buttons">
					<button @click="startRecording('tab')" class="option-btn">
						<span class="icon">📄</span>
						当前标签页
					</button>
					<button @click="startRecording('window')" class="option-btn">
						<span class="icon">🖥️</span>
						整个桌面
					</button>
					<button @click="startRecording('application')" class="option-btn">
						<span class="icon">📱</span>
						应用窗口
					</button>
				</div>

				<div class="settings">
					<label>
						录制时长 (秒):
						<input
							v-model.number="recordDuration"
							type="number"
							min="1"
							max="60"
						/>
					</label>
				</div>
			</div>

			<div v-if="isRecording" class="recording">
				<div class="recording-indicator">
					<span class="pulse"></span>
					正在录制...
				</div>
				<div class="timer">{{ formatTime(recordedTime) }}</div>
				<button @click="stopRecording" class="stop-btn">停止录制</button>
			</div>

			<div v-if="gifPreview" class="preview">
				<h3>GIF 预览</h3>
				<img :src="gifPreview" alt="GIF预览" class="gif-preview" />
				<div class="preview-actions">
					<button @click="saveGif" class="save-btn">保存 GIF</button>
					<button @click="reset" class="reset-btn">重新录制</button>
				</div>
			</div>

			<div v-if="isProcessing" class="processing">
				<div class="loader"></div>
				<p>正在生成 GIF...</p>
			</div>
		</div>
	</div>
</template>

<script setup lang="ts">
import { ref, onUnmounted } from "vue";
import { generateGif } from "@/utils/gifGenerator";

const isRecording = ref(false);
const recordedTime = ref(0);
const recordDuration = ref(10);
const gifPreview = ref<string | null>(null);
const isProcessing = ref(false);

let mediaRecorder: MediaRecorder | null = null;
let recordedChunks: Blob[] = [];
let timer: number | null = null;

const formatTime = (seconds: number) => {
	const mins = Math.floor(seconds / 60);
	const secs = seconds % 60;
	return `${mins.toString().padStart(2, "0")}:${secs
		.toString()
		.padStart(2, "0")}`;
};

const startRecording = async (type: "tab" | "window" | "application") => {
	try {
		const constraints: DisplayMediaStreamOptions = {
			video: true,
			audio: false,
		};

		const stream = await navigator.mediaDevices.getDisplayMedia(constraints);

		recordedChunks = [];
		recordedTime.value = 0;
		isRecording.value = true;

		mediaRecorder = new MediaRecorder(stream, {
			mimeType: "video/webm",
		});

		mediaRecorder.ondataavailable = (event) => {
			if (event.data.size > 0) {
				recordedChunks.push(event.data);
			}
		};

		mediaRecorder.onstop = async () => {
			stream.getTracks().forEach((track) => track.stop());
			await processRecording();
		};

		mediaRecorder.start();

		timer = window.setInterval(() => {
			recordedTime.value++;
			if (recordedTime.value >= recordDuration.value) {
				stopRecording();
			}
		}, 1000);
	} catch (err) {
		console.error("录制失败:", err);
		alert(
			"录制失败，请检查权限设置: " +
				(err instanceof Error ? err.message : String(err))
		);
	}
};

const stopRecording = () => {
	if (mediaRecorder && mediaRecorder.state === "recording") {
		mediaRecorder.stop();
	}

	if (timer) {
		clearInterval(timer);
		timer = null;
	}

	isRecording.value = false;
};

const processRecording = async () => {
	if (recordedChunks.length === 0) return;

	isProcessing.value = true;

	try {
		const blob = new Blob(recordedChunks, { type: "video/webm" });
		const gifBlob = await generateGif(blob);

		const reader = new FileReader();
		reader.onload = () => {
			gifPreview.value = reader.result as string;
			isProcessing.value = false;
		};
		reader.readAsDataURL(gifBlob);
	} catch (err) {
		console.error("GIF生成失败:", err);
		alert("GIF生成失败: " + (err instanceof Error ? err.message : String(err)));
		isProcessing.value = false;
	}
};

const saveGif = async () => {
	if (!gifPreview.value) return;

	try {
		// 使用 browser API 进行保存
		const response = await browser.runtime.sendMessage({
			type: "SAVE_GIF",
			dataUrl: gifPreview.value,
			filename: `gifshot-${Date.now()}.gif`,
		});

		if (response.success) {
			alert("GIF 保存成功！");
		} else {
			throw new Error(response.error || "保存失败");
		}
	} catch (err) {
		console.error("保存失败:", err);
		alert("保存失败: " + (err instanceof Error ? err.message : String(err)));
	}
};

const reset = () => {
	gifPreview.value = null;
	recordedTime.value = 0;
	recordedChunks = [];
};

const openFullApp = async () => {
	try {
		await browser.tabs.create({
			url: browser.runtime.getURL("app.html"),
		});
	} catch (error) {
		console.error("打开完整版失败:", error);
		alert(
			"打开完整版失败: " +
				(error instanceof Error ? error.message : String(error))
		);
	}
};

onUnmounted(() => {
	if (timer) {
		clearInterval(timer);
	}
	if (mediaRecorder && mediaRecorder.state === "recording") {
		mediaRecorder.stop();
	}
});
</script>

// tabs/app.tsx
import React, { useState, useEffect, useRef } from "react"

import { generateGif } from "../utils/gifGenerator"
import "./app.less"

function AppPage() {
  const [isRecording, setIsRecording] = useState(false)
  const [recordedTime, setRecordedTime] = useState(0)
  const [recordDuration, setRecordDuration] = useState(10)
  const [frameRate, setFrameRate] = useState(8)
  const [gifPreview, setGifPreview] = useState<string | null>(null)
  const [isProcessing, setIsProcessing] = useState(false)
  const [processingStatus, setProcessingStatus] = useState("准备中...")
  const [gifSize, setGifSize] = useState("")
  const [gifDimensions, setGifDimensions] = useState("")

  const mediaRecorderRef = useRef<MediaRecorder | null>(null)
  const recordedChunksRef = useRef<Blob[]>([])
  const timerRef = useRef<number | null>(null)

  useEffect(() => {
    return () => {
      if (timerRef.current) {
        clearInterval(timerRef.current)
      }
      if (mediaRecorderRef.current && mediaRecorderRef.current.state === "recording") {
        mediaRecorderRef.current.stop()
      }
    }
  }, [])

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60)
    const secs = seconds % 60
    return `${mins.toString().padStart(2, "0")}:${secs
      .toString()
      .padStart(2, "0")}`
  }

  const formatFileSize = (bytes: number) => {
    if (bytes === 0) return "0 Bytes"
    const k = 1024
    const sizes = ["Bytes", "KB", "MB", "GB"]
    const i = Math.floor(Math.log(bytes) / Math.log(k))
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + " " + sizes[i]
  }

  const openPopup = () => {
    chrome.action.openPopup()
  }

  const startRecording = async (type: "tab" | "window" | "application") => {
    try {
      setProcessingStatus("请求屏幕权限...")

      const constraints: MediaStreamConstraints = {
        video: {
          // @ts-ignore
          mediaSource: type === "tab" ? "tab" : "screen"
        },
        audio: false
      }

      const stream = await navigator.mediaDevices.getDisplayMedia(constraints)

      recordedChunksRef.current = []
      setRecordedTime(0)
      setIsRecording(true)

      mediaRecorderRef.current = new MediaRecorder(stream, {
        mimeType: "video/webm"
      })

      mediaRecorderRef.current.ondataavailable = (event) => {
        if (event.data.size > 0) {
          recordedChunksRef.current.push(event.data)
        }
      }

      mediaRecorderRef.current.onstop = async () => {
        stream.getTracks().forEach((track) => track.stop())
        await processRecording()
      }

      mediaRecorderRef.current.start()

      timerRef.current = window.setInterval(() => {
        setRecordedTime((prev) => {
          const newTime = prev + 1
          if (newTime >= recordDuration) {
            stopRecording()
          }
          return newTime
        })
      }, 1000)
    } catch (err) {
      console.error("录制失败:", err)
      alert("录制失败，请检查权限设置")
    }
  }

  const stopRecording = () => {
    if (mediaRecorderRef.current && mediaRecorderRef.current.state === "recording") {
      mediaRecorderRef.current.stop()
    }

    if (timerRef.current) {
      clearInterval(timerRef.current)
      timerRef.current = null
    }

    setIsRecording(false)
  }

  const processRecording = async () => {
    if (recordedChunksRef.current.length === 0) return

    setIsProcessing(true)
    setProcessingStatus("正在处理视频...")

    try {
      const blob = new Blob(recordedChunksRef.current, { type: "video/webm" })
      console.log("开始处理视频，大小:", formatFileSize(blob.size))

      setProcessingStatus("正在生成 GIF...")
      const gifBlob = await generateGif(blob)

      // 获取图片信息
      const img = new Image()
      img.onload = () => {
        setGifDimensions(`${img.width} x ${img.height}`)
      }

      setGifSize(formatFileSize(gifBlob.size))

      const reader = new FileReader()
      reader.onload = () => {
        setGifPreview(reader.result as string)
        img.src = reader.result as string
        setIsProcessing(false)
        setProcessingStatus("")
      }
      reader.readAsDataURL(gifBlob)
    } catch (err) {
      console.error("GIF生成失败:", err)
      alert(`GIF生成失败: ${err instanceof Error ? err.message : String(err)}`)
      setIsProcessing(false)
    }
  }

  const saveGif = async () => {
    if (!gifPreview) return

    try {
      const response = await fetch(gifPreview)
      const blob = await response.blob()

      const url = URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = `gifshot-${Date.now()}.gif`
      a.click()

      URL.revokeObjectURL(url)
    } catch (err) {
      console.error("保存失败:", err)
      alert("保存失败")
    }
  }

  const reset = () => {
    setGifPreview(null)
    setRecordedTime(0)
    recordedChunksRef.current = []
    setGifSize("")
    setGifDimensions("")
  }

  return (
    <div className="app-container">
      <header className="app-header">
        <div className="logo">
          <h1>🎬 GifShot</h1>
          <p>屏幕录制 GIF 插件</p>
        </div>
        <div className="actions">
          <button onClick={openPopup} className="btn-secondary">
            弹窗模式
          </button>
        </div>
      </header>

      <main className="app-main">
        {!isRecording && !gifPreview && (
          <div className="record-section">
            <h2>选择录制类型</h2>
            <div className="record-grid">
              <div className="record-card" onClick={() => startRecording("tab")}>
                <div className="card-icon">📄</div>
                <h3>当前标签页</h3>
                <p>录制当前浏览器标签页内容</p>
              </div>
              <div className="record-card" onClick={() => startRecording("window")}>
                <div className="card-icon">🖥️</div>
                <h3>整个桌面</h3>
                <p>录制整个桌面屏幕</p>
              </div>
              <div className="record-card" onClick={() => startRecording("application")}>
                <div className="card-icon">📱</div>
                <h3>应用窗口</h3>
                <p>录制特定应用程序窗口</p>
              </div>
            </div>

            <div className="settings-panel">
              <h3>录制设置</h3>
              <div className="setting-item">
                <label>录制时长 (秒):</label>
                <input
                  value={recordDuration}
                  onChange={(e) => setRecordDuration(Number(e.target.value))}
                  type="number"
                  min="1"
                  max="60"
                  className="setting-input"
                />
              </div>
              <div className="setting-item">
                <label>帧率:</label>
                <select
                  value={frameRate}
                  onChange={(e) => setFrameRate(Number(e.target.value))}
                  className="setting-select">
                  <option value="5">5 FPS (文件小)</option>
                  <option value="8">8 FPS (推荐)</option>
                  <option value="10">10 FPS (文件大)</option>
                </select>
              </div>
            </div>
          </div>
        )}

        {isRecording && (
          <div className="recording-section">
            <div className="recording-display">
              <div className="recording-indicator">
                <span className="pulse"></span>
                <span className="text">正在录制...</span>
              </div>
              <div className="timer">{formatTime(recordedTime)}</div>
              <div className="progress-bar">
                <div
                  className="progress-fill"
                  style={{ width: (recordedTime / recordDuration) * 100 + "%" }}
                ></div>
              </div>
              <button onClick={stopRecording} className="btn-stop">
                ⏹️ 停止录制
              </button>
            </div>
          </div>
        )}

        {isProcessing && (
          <div className="processing-section">
            <div className="processing-display">
              <div className="loader"></div>
              <h3>正在生成 GIF...</h3>
              <p className="progress-text">{processingStatus}</p>
            </div>
          </div>
        )}

        {gifPreview && (
          <div className="preview-section">
            <h2>GIF 预览</h2>
            <div className="preview-container">
              <img src={gifPreview} alt="GIF预览" className="gif-preview" />
              <div className="preview-info">
                <p>大小: {gifSize}</p>
                <p>尺寸: {gifDimensions}</p>
              </div>
            </div>
            <div className="preview-actions">
              <button onClick={saveGif} className="btn-primary">
                💾 保存 GIF
              </button>
              <button onClick={reset} className="btn-secondary">
                🔄 重新录制
              </button>
            </div>
          </div>
        )}
      </main>

      <footer className="app-footer">
        <p>&copy; 2024 GifShot. Made with ❤️</p>
      </footer>
    </div>
  )
}

export default AppPage
